from __future__ import annotations

from dataclasses import dataclass


# BETO-TRACE: BETO_REPEATED_LOG_MONITOR.SEC4.UNIT.LOG_LINE_CANDIDATE_ERROR_EVENT
# BETO-TRACE: BETO_REPEATED_LOG_MONITOR.SEC4.FIELD.RAW_LOG_LINE_CONTENT
# BETO-TRACE: BETO_REPEATED_LOG_MONITOR.SEC4.FIELD.DETECTION_TIMESTAMP
# BETO-TRACE: BETO_REPEATED_LOG_MONITOR.SEC4.TRACE_FIELD.SOURCE_LOG_FILE_PATH
# BETO-TRACE: BETO_REPEATED_LOG_MONITOR.SEC4.TRACE_FIELD.MATCHED_PATTERN_STRING
# BETO-TRACE: BETO_REPEATED_LOG_MONITOR.SEC8.DECISION.OUTPUT_FILE_MODELS_PY
@dataclass(frozen=True)
class LogEvent:
    source_path: str
    detection_timestamp: float
    raw_line: str
    pattern: str


# BETO-TRACE: BETO_REPEATED_LOG_MONITOR.SEC6.CONCEPT.ALERT_EVENT
# BETO-TRACE: BETO_REPEATED_LOG_MONITOR.SEC3.OUTPUT.LOCAL_CONSOLE_ALERT
# BETO-TRACE: BETO_REPEATED_LOG_MONITOR.SEC3.OUTPUT.PERSISTED_ALERT_EVENT
# BETO-TRACE: BETO_REPEATED_LOG_MONITOR.SEC8.DECISION.OUTPUT_FILE_MODELS_PY
@dataclass(frozen=True)
class AlertEvent:
    pattern: str
    count: int
    window_seconds: int
    first_seen_timestamp: float
    last_seen_timestamp: float
